<?php

namespace common\models\cms;

use common\models\cms\dao\TblCmsFields;

class Field extends TblCmsFields
{
    public function afterFind()
    {
        if(!empty($this->settings)){
            $this->settings = json_decode($this->settings, true);
        }
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * @return null
     */
    public function getInputType()
    {
        return $this->getFieldAttribute('input_type');
    }

    public function getFieldAttribute($name)
    {
        return isset($this->settings[$name])?$this->settings[$name]:null;
    }

	/**
	 * Find by id
	 * @param $id
	 *
	 * @return null|static
	 */
    public static function findById($id)
    {
    	return self::findOne(['id' => $id]);
    }

	/**
	 * @param $code
	 *
	 * @return int|null
	 */
    public static function getIdByCode($code)
    {
        $model = self::findOne(['code' => $code]);
        if($model !== null){
            return $model->id;
        }
        return null;
    }
}